name: delivit
description: Delivery app - community based - final work deneubourg mohamed yassine
version: 1.0.0+1

module:
  androidX: true

environment:
  sdk: ">=2.3.0"

dependencies:
  flutter:
    sdk: flutter
  # inschrijving en login + FIREBASE:
  international_phone_input: ^1.0.2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.0.8
  # Kaart:
  flutter_map: any
  geopoint: ^0.7.0
  geolocator: ^5.1.5
  location_permissions: ^2.0.4+1
  app_settings: ^3.0.0+1
  datetime_picker_formfield: ^1.0.0
  bubble: ^1.1.9+1
  #NOTIFICATIONS:
  flutter_local_notifications: ^1.2.2
  flutter_app_badger: ^1.1.2
  #AFBEELDINGEN
  image_picker: ^0.6.3+4
  flutter_native_image: ^0.0.5
  # Algemene:
  flutter_launcher_icons: "^0.7.3"
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  toast: ^0.1.5
  icon_shadow: ^1.0.1
  flutter_spinkit: "^4.1.1"
  curved_navigation_bar: ^0.3.1
  flutter_rating_bar: ^3.0.1+1
  dotted_border: ^1.0.4
  dio: ^3.0.8
  flutter_staggered_grid_view: ^0.3.0
  android_intent: ^0.3.5
  url_launcher: ^5.2.5
  keyboard_avoider: ^0.1.2
  lottie: ^0.3.2
  expandable: ^4.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

  assets:
    - assets/images/
    - assets/Animations/

  uses-material-design: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
